# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np

In [11]:
data = np.random.uniform(0, 20, size = (4, 7))
print(data)
(data-np.min(data))/(np.max(data)-np.min(data))

[[ 3.30052352 15.63190401 12.77626992 10.60418555 15.83036653  1.93429933
   8.22283354]
 [ 4.99911009  8.72810044 16.12866321 16.0739754  18.24753364 16.29411866
  12.82822087]
 [18.49936435  9.63054908 11.01862015  4.37133298 14.20054075 17.51468119
   0.29267968]
 [ 9.12243354 16.37553478 11.99305134  1.09629335  3.09251255  7.17979275
   8.25933107]]


array([[0.16520547, 0.84250508, 0.68565972, 0.56635824, 0.85340561,
        0.09016577, 0.43556276],
       [0.25850013, 0.46331449, 0.86978952, 0.8667858 , 0.98616823,
        0.87887714, 0.68851312],
       [1.        , 0.51288137, 0.58912101, 0.22401955, 0.76388762,
        0.94591639, 0.        ],
       [0.48497318, 0.88334891, 0.64264153, 0.04413839, 0.15378049,
        0.37827387, 0.43756738]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [12]:
arr = np.random.randint(0, 10, size = (8, 10))
print(arr)
print("Row Index",np.argmin(np.sum(arr, axis=1)))
arr[np.argmin(np.sum(arr, axis=1))]

[[6 0 2 7 1 5 9 1 5 1]
 [6 6 3 3 1 1 3 5 2 7]
 [5 9 8 5 6 4 3 6 9 6]
 [5 0 4 4 4 2 0 9 8 4]
 [2 4 8 4 9 9 0 4 9 3]
 [5 4 5 8 0 6 2 5 8 8]
 [5 8 2 8 4 6 0 4 0 5]
 [2 1 6 7 4 9 0 2 4 5]]
Row Index 0


array([6, 0, 2, 7, 1, 5, 9, 1, 5, 1])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [13]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D
point_1 = np.random.randint(0, 20, size=5)
point_2 = np.random.randint(0, 20, size=5)
print(point_1)
print(point_2)
#first way
square = np.square(point_1 - point_2)
sum_square = np.sum(square)
print(np.sqrt(sum_square))
#second way
distance = np.linalg.norm(point_1-point_2)
print(distance)

[ 3  4 16 12  7]
[18 11  6 18 19]
23.53720459187964
23.53720459187964


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [14]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
#решение: x = a^-1*(-c)*b^-1

x0 = np.matmul(np.linalg.inv(a),(-c))
print(x0)
x =  np.matmul(x0,np.linalg.inv(b))
print(x)

[[ 3. -1.]
 [-4.  3.]
 [ 1. -7.]]
[[ 1.00000000e+00  1.11022302e-15]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [19]:
import numpy as np
data = np.loadtxt('minutes_n_ingredients.csv', dtype='int32', delimiter=",", skiprows=1)
print(data[:5,])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [7]:
new = data[:,1:]
average = np.average(new, axis=0)

min = np.min(new, axis=0)

max = np.max(new, axis=0)

median = np.median(new, axis=0)

print("Среднее значение, минимум, максимум, медиана")
print(average)
print(min)
print(max)
print(median)

Среднее значение, минимум, максимум, медиана
[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [8]:
np.clip(data[:,1], 0, np.quantile(data[:, 1], 0.75, method='higher'))

array([60, 25, 10, ..., 65,  5, 65])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [37]:
minutes_zeros = data[:, 1]

bool_arr = (minutes_zeros == 0)
# количество рецептов, для которых продолжительность равна нулю
count_zeros = np.count_nonzero(bool_arr)
print(count_zeros) # 479

# замена всех нулей на единицы
minutes_zeros[minutes_zeros == 0] = 1
# подсчет нулей и вывод
count_zeros_new = np.count_nonzero(bool_arr)
# нулей больше нет в массиве данных
print(count_zeros_new)

0
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [59]:
ids = data[:, 0]
count = len(np.unique(ids))
print(count)

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [60]:
n_ingredients = data[:,2]
unique_n_ingredients = np.unique(n_ingredients)
count = len(unique_n_ingredients)

print(unique_n_ingredients)
print(count)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [21]:
data[np.where(data[:, 2] <= 5)]

[[     0      0      0]
 [446597     15      5]
 [204134      5      3]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [43]:
new = np.array([data[:,2] / data[:,1]])
max_value = new.max(axis=1)
print(new)
print(max_value)

[[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]]
[24.]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [55]:
# сортировка по убывания по второму столбцу (минуты)
sorted_by_minutes = data[data[:,1].argsort()[::-1]]
#  создаем массив ингредиентов из отсортированного массива
top100_only_ingredients = sorted_by_minutes[:100,2]
# находим среднее кол-во ингредиентов
average_top100 = np.mean(top100_only_ingredients)
# вывод
print(average_top100)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [64]:
for i in range(10):
    print(data[np.random.randint(len(data))])

[163071     10      6]
[265531     70      7]
[403404      5      4]
[53920    35     6]
[292286      5      7]
[398943    490      7]
[517553     75      7]
[320154     30      4]
[194584     45     12]
[305724     25      9]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [105]:
# среднее кол-во ингредиентов
mean_value = data[:,2].mean()

c = np.count_nonzero(data[:,2] < mean_value)
result = c / len(data) * 100
print(result,"%")

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [55]:

x, y = data[:,1], data[:,2]
new = np.where((x <= 20) & (y <= 5), 1, 0)[:, np.newaxis]
simple_recipes = np.hstack((data, new))

print(simple_recipes)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [10]:
result = simple_recipes[:,3].sum() / len(data) * 100
print(result, '%')

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [53]:
# копируем датасет для работы
new_data = data.copy()
# создаем столбец с группами по продолжительности 0, 1, 2
axis1 = np.where(new_data[:,1] < 10, 0, np.where((new_data[:,1] >= 10) & (new_data[:,1] < 20), 1, 2))
# добавляем столбец с указанием группы к основному датасету
res = np.hstack((new_data, axis1[:, np.newaxis]))
# ищем количество рецептов с определенной группой
count1 = np.count_nonzero(res[:,3] == 0)
count2 = np.count_nonzero(res[:,3] == 1)
count3 = np.count_nonzero(res[:,3] == 2)
# находим минимальное среди кол-ва трех групп, это и будет наше максимальное количество рецептов из каждой группы
step = np.array([count1, count2, count3]).min() 
res = res[res[:,3].argsort()] # сортировка по 4 столбцу (нашим группам по продолжительности)
# с помощью найденного количества рецептов по каждой группе создаем срезы и делаем трехмерный массив
result = np.stack((res[:step, :3], res[count1+1:count1+1+step,:3], res[count1+count2:count1+count2+step,:3]))
print(result)
print(result.shape)

[[[ 77618      5      6]
  [ 34121      5      3]
  [ 95926      5      3]
  ...
  [  3252      0     10]
  [227475      5      8]
  [459324      2      4]]

 [[226305     10      7]
  [153159     17     10]
  [259876     15      6]
  ...
  [168154     14      4]
  [ 68467     17      9]
  [  2815     10      9]]

 [[153966     45     11]
  [204566     45     13]
  [ 47319     40     12]
  ...
  [279870     45     15]
  [417697     25      5]
  [224701    492      7]]]
(3, 7588, 3)
